/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainGui;

import AddtionGui.AddGuiFactory;
import AddtionGui.AddNewCustomer;
import AddtionGui.AddNewDepartment;
import AddtionGui.AddnewProduct;
import Database.DBMaker;
import Entities.Customer;
import Entities.Department;
import Entities.Product;
import Observers.CustomerObserver;
import Observers.DepartmentObserver;
import Observers.ProductObserver;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Manager_Window extends javax.swing.JFrame {

    public static DefaultListModel<String> DepartmentModel;
    public static DefaultListModel<String> CustomerModel;
    public static DefaultListModel<String> ProductModel;
    public static DefaultComboBoxModel<String> DepaertmentsComboBoxModel;
    private static DBMaker dBMaker;
    private int SelectedDepartmentId;
    private Department selectedDepartmentFromList;
    private int SelectedCustomerId;
    private Customer selectedCustomer;
    private Product selectedProdcut;
    private int selectedProdcutId;

    public Manager_Window() {
        initComponents();
        GuiMethods.addWindowListener(this);
        intialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DepartmentList = new javax.swing.JList<>();
        addNewDepartmentButton = new javax.swing.JButton();
        updateDepartmentButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        departmentNameFeild = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DepDescriptionArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        deleteDepartmentButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        productNameField = new javax.swing.JTextField();
        productPriceField = new javax.swing.JTextField();
        productQuantityField = new javax.swing.JTextField();
        departmentComobox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        productdescriptionTextarea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        addNewProductButton = new javax.swing.JButton();
        updateProductButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        deleteProductButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CustomerList = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CustomerNameField = new javax.swing.JTextField();
        CustomerAdderssfield = new javax.swing.JTextField();
        CustomerUnamefield = new javax.swing.JTextField();
        CustomerPasswordField = new javax.swing.JTextField();
        addNewCustomerButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        CustomerIdField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CustomerBalanceField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TransactionTable = new javax.swing.JTable();
        deleteTransactionsButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Depatment List");

        DepartmentList.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DepartmentListComponentAdded(evt);
            }
        });
        DepartmentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartmentListMouseClicked(evt);
            }
        });
        DepartmentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DepartmentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DepartmentList);

        addNewDepartmentButton.setText("Add new Department ");
        addNewDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDepartmentButtonActionPerformed(evt);
            }
        });

        updateDepartmentButton.setText("Update  Department");
        updateDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDepartmentButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Department name:");

        departmentNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameFeildActionPerformed(evt);
            }
        });

        DepDescriptionArea.setColumns(20);
        DepDescriptionArea.setRows(5);
        jScrollPane2.setViewportView(DepDescriptionArea);

        jLabel3.setText("Description:");

        deleteDepartmentButton.setText("Delete Department");
        deleteDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDepartmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addNewDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteDepartmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departmentNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Depatment", jPanel1);

        jLabel4.setText("Product Name:");

        jLabel5.setText("Price:");

        jLabel6.setText("Quantity");

        jLabel7.setText("Department:");

        jLabel8.setText("Description:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        productQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityFieldActionPerformed(evt);
            }
        });

        productdescriptionTextarea.setColumns(20);
        productdescriptionTextarea.setRows(5);
        jScrollPane4.setViewportView(productdescriptionTextarea);

        addNewProductButton.setText("Add new Product");
        addNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProductButtonActionPerformed(evt);
            }
        });

        updateProductButton.setText("Update Product");
        updateProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductButtonActionPerformed(evt);
            }
        });

        ProductList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ProductList);

        jLabel9.setText("Product List");

        deleteProductButton.setText("Delete Product");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productPriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(productQuantityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(departmentComobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addNewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(productPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(productQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(departmentComobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Product", jPanel2);

        jLabel10.setText("Customer List");

        CustomerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerListMouseClicked(evt);
            }
        });
        CustomerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CustomerListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(CustomerList);

        jLabel11.setText("Customer Name:");

        jLabel12.setText("Address:");

        jLabel13.setText("Username:");

        jLabel14.setText("Password:");

        CustomerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameFieldActionPerformed(evt);
            }
        });

        addNewCustomerButton.setText("Add new Customer");
        addNewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCustomerButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("Update Customer");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("Delete Customer");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("ID:");

        jLabel17.setText("Balance :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)))
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(addNewCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CustomerNameField)
                                .addComponent(CustomerAdderssfield)
                                .addComponent(CustomerUnamefield)
                                .addComponent(CustomerPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(CustomerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CustomerBalanceField))
                            .addComponent(updateCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustomerIdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerAdderssfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerUnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CustomerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(CustomerBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomerButton)
                    .addComponent(addNewCustomerButton)
                    .addComponent(updateCustomerButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel3);

        TransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Quntity", "Product", "Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TransactionTable);

        deleteTransactionsButton.setText("Delete Transactions");
        deleteTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTransactionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(deleteTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(deleteTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transactions", jPanel5);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.lightGray);
        jLabel16.setText("Welcome Manager \")");

        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameFeildActionPerformed

    private void addNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProductButtonActionPerformed
        // TODO add your handling code here:
        AddGuiFactory.getAddGui(AddGuiFactory.addNewProduct).setVisible(true);
    }//GEN-LAST:event_addNewProductButtonActionPerformed

    private void productQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQuantityFieldActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        String selectedProduct = ProductList.getSelectedValue();
        if (selectedProduct == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to Update this Product", "Update Product",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dBMaker.deleteProductMaker(selectedProduct);
            new ProductObserver(selectedProdcut).update();
            GuiMethods.emptyFields(productNameField, productPriceField, productQuantityField);
            productdescriptionTextarea.setText("");

        }

    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void CustomerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameFieldActionPerformed

    private void addNewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCustomerButtonActionPerformed
        // TODO add your handling code here:
        AddGuiFactory.getAddGui(AddGuiFactory.addNewCustomer).setVisible(true);
    }//GEN-LAST:event_addNewCustomerButtonActionPerformed

    private void addNewDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDepartmentButtonActionPerformed
        // TODO add your handling code here:
        AddGuiFactory.getAddGui(AddGuiFactory.addNewDepartment).setVisible(true);
    }//GEN-LAST:event_addNewDepartmentButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        if (GuiMethods.isEmptyFields(this, CustomerAdderssfield, CustomerNameField, CustomerUnamefield, CustomerPasswordField, CustomerIdField, CustomerBalanceField)) {
            return;
        }
        try {
            Double.parseDouble(CustomerBalanceField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad inputs", "bad inputs", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String selectedCustomerName = CustomerList.getSelectedValue();
        if (selectedCustomerName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
               
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to Update this Customer", "Update Customer",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            Customer aCustomer = (Customer) new Customer().
                    setAdress(CustomerAdderssfield.getText()).
                    setBalance(Double.parseDouble(CustomerBalanceField.getText())).
                    setName(CustomerNameField.getText()).
                    setUserName(CustomerUnamefield.getText()).
                    setPassword(CustomerPasswordField.getText()).
                    setId(Integer.parseInt(CustomerIdField.getText()));
            dBMaker.updateCustomerMaker(aCustomer);
            new CustomerObserver(selectedCustomer).update();
            GuiMethods.emptyFields(CustomerAdderssfield, CustomerNameField, CustomerUnamefield, CustomerPasswordField, CustomerIdField, CustomerBalanceField);
        }
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void DepartmentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DepartmentListValueChanged
    }//GEN-LAST:event_DepartmentListValueChanged

    private void DepartmentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentListMouseClicked
        // TODO add your handling code here:
        String selectedDepName = DepartmentList.getSelectedValue();
        if (selectedDepName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        selectedDepName = DepartmentList.getSelectedValue();
        selectedDepartmentFromList = dBMaker.getDepartmentMaker(selectedDepName);
        departmentNameFeild.setText(selectedDepartmentFromList.getName());
        DepDescriptionArea.setText(selectedDepartmentFromList.getDescription());
        SelectedDepartmentId = selectedDepartmentFromList.getDid();
    }//GEN-LAST:event_DepartmentListMouseClicked

    private void deleteDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDepartmentButtonActionPerformed
        // TODO add your handling code here:
        String selectedDepName = DepartmentList.getSelectedValue();
        if (selectedDepName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to remove this Department", "Delete Department",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dBMaker.deleteDepartmentMaker(SelectedDepartmentId);
            new DepartmentObserver(selectedDepartmentFromList).update();
            departmentNameFeild.setText("");
            DepDescriptionArea.setText("");
            GuiMethods.emptyFields(productNameField, productPriceField, productQuantityField);
            productdescriptionTextarea.setText("");
        }
    }//GEN-LAST:event_deleteDepartmentButtonActionPerformed

    private void updateDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDepartmentButtonActionPerformed
        if (GuiMethods.isEmptyFields(this, departmentNameFeild)) {
            return;
        }
        String selectedDepName = DepartmentList.getSelectedValue();
        if (selectedDepName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
      
        }
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to Update this Department", "Update Department",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dBMaker.updateDepartmentMaker(departmentNameFeild.getText(), DepDescriptionArea.getText(), SelectedDepartmentId);
            new DepartmentObserver(selectedDepartmentFromList).update();
            GuiMethods.emptyFields(departmentNameFeild);
            DepDescriptionArea.setText("");
        }
    }//GEN-LAST:event_updateDepartmentButtonActionPerformed

    private void CustomerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerListMouseClicked
        // TODO add your handling code here:
        String CustomerName = CustomerList.getSelectedValue();
        if (CustomerName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CustomerName = CustomerList.getSelectedValue();
        selectedCustomer = dBMaker.getCustomerMaker(CustomerName);
        CustomerIdField.setText(String.valueOf(selectedCustomer.getId()));
        CustomerUnamefield.setText(selectedCustomer.getUserName());
        CustomerAdderssfield.setText(selectedCustomer.getAddress());
        CustomerNameField.setText(selectedCustomer.getName());
        CustomerPasswordField.setText(selectedCustomer.getPassword());
        CustomerBalanceField.setText(String.valueOf(selectedCustomer.getBalance()));
        SelectedCustomerId = selectedCustomer.getId();

    }//GEN-LAST:event_CustomerListMouseClicked

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        // TODO add your handling code here:
        String selectedCustomerName = CustomerList.getSelectedValue();
        if (selectedCustomerName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to Delete this Customer", "Delete Customer",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dBMaker.deleteCustomerMaker(SelectedCustomerId);
            new CustomerObserver(selectedCustomer).update();
            GuiMethods.emptyFields(CustomerAdderssfield, CustomerIdField, CustomerNameField, CustomerUnamefield, CustomerPasswordField);
        }
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void updateProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductButtonActionPerformed
        if (GuiMethods.isEmptyFields(this, productNameField, productPriceField, productQuantityField)) {
            return;
        }
        String selectedProductName = ProductList.getSelectedValue();
        if (selectedProductName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Integer.parseInt(productQuantityField.getText());
            Double.parseDouble(productPriceField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad inputs", "Bad inputs", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null,
                "Are you sure you want to Update this product", "Update product",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dBMaker.updateProductMaker(productNameField.getText(), Double.parseDouble(productPriceField.getText()), Integer.parseInt(productQuantityField.getText()), dBMaker.getDepartmentMaker((String) departmentComobox.getSelectedItem()).getDid(), productdescriptionTextarea.getText(), selectedProdcut.getPid());
            new ProductObserver(selectedProdcut).update();
            GuiMethods.emptyFields(productNameField, productPriceField, productQuantityField);
            productdescriptionTextarea.setText("");
        }

    }//GEN-LAST:event_updateProductButtonActionPerformed

    private void CustomerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CustomerListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerListValueChanged

    private void DepartmentListComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DepartmentListComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentListComponentAdded

    private void ProductListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductListMouseClicked
        String seletedProductName = ProductList.getSelectedValue();
        if (seletedProductName == null) {
            JOptionPane.showMessageDialog(this, "Empty Fields", "Something is messing", JOptionPane.ERROR_MESSAGE);
            return;
        }
        seletedProductName = ProductList.getSelectedValue();
        selectedProdcut = dBMaker.getProductMaker(seletedProductName);
        productNameField.setText(seletedProductName);
        selectedProdcutId = selectedProdcut.getPid();
        productPriceField.setText(selectedProdcut.getPrice() + "");
        productdescriptionTextarea.setText(selectedProdcut.getProductDescription());
        productQuantityField.setText(selectedProdcut.getQuantity() + "");
        departmentComobox.setSelectedItem(dBMaker.getDepartmentMaker(selectedProdcut.getdId()).getName());
    }//GEN-LAST:event_ProductListMouseClicked

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        GuiMethods.Logout(this);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void deleteTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTransactionsButtonActionPerformed
        dBMaker.deleteAllTransactionsMaker();
        dBMaker.getAllTransactionsMaker(TransactionTable);
    }//GEN-LAST:event_deleteTransactionsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Window.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Window().setVisible(true);

            }
        });
    }
    private final Thread t = new Thread() {
        @Override
        public void run() {
            while (true) {
                Date date = new Date();
                String strDateFormat = "hh:mm:ss a";
                DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
                String formattedDate = dateFormat.format(date);
                TimeLabel.setText("Time : " + formattedDate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println(ex);
                }
            }
        }
    };
    private final Thread t2 = new Thread() {
        @Override
        public void run() {
            while (true) {
                dBMaker.getAllTransactionsMaker(TransactionTable);
                try {
                    Thread.sleep(5000);

                } catch (InterruptedException ex) {
                    System.out.println(ex);
                }

            }
        }
    };

    public void intialization() {
        CustomerIdField.setEditable(false);
        setTitle("Manager Widnow");
        setVisible(true);
        DepartmentModel = new DefaultListModel<>();
        CustomerModel = new DefaultListModel<>();
        ProductModel = new DefaultListModel<>();
        DepaertmentsComboBoxModel = new DefaultComboBoxModel<>();
        DepartmentList.setModel(DepartmentModel);
        ProductList.setModel(ProductModel);
        CustomerList.setModel(CustomerModel);
        departmentComobox.setModel(DepaertmentsComboBoxModel);
        GuiMethods.viewDepartmentList();
        GuiMethods.viewCustomerList();
        GuiMethods.viewProductList();
        new GuiMethods().setIcon(LogoutButton, "imgs/index.png", 100, 50);
        dBMaker = DBMaker.getDBMaker();
        t.start();
        t2.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerAdderssfield;
    private javax.swing.JTextField CustomerBalanceField;
    private javax.swing.JTextField CustomerIdField;
    private javax.swing.JList<String> CustomerList;
    private javax.swing.JTextField CustomerNameField;
    private javax.swing.JTextField CustomerPasswordField;
    private javax.swing.JTextField CustomerUnamefield;
    private javax.swing.JTextArea DepDescriptionArea;
    private javax.swing.JList<String> DepartmentList;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JList<String> ProductList;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JTable TransactionTable;
    private javax.swing.JButton addNewCustomerButton;
    private javax.swing.JButton addNewDepartmentButton;
    private javax.swing.JButton addNewProductButton;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteDepartmentButton;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JButton deleteTransactionsButton;
    private javax.swing.JComboBox<String> departmentComobox;
    private javax.swing.JTextField departmentNameFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JTextField productQuantityField;
    private javax.swing.JTextArea productdescriptionTextarea;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateDepartmentButton;
    private javax.swing.JButton updateProductButton;
    // End of variables declaration//GEN-END:variables

}
